version: "3.8"

services:
  backend:
    build: ./backend
    container_name: autobook-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8
    container_name: autobook-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wmhmw
      MYSQL_DATABASE: autobook
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: